### ISSUE TITLE
Arch Linux build error

### ISSUE THREAD

**Issue by c4dr01d** [cdepillabout/termonad#169] opened 2020-09-24 04:48 UTC
I following the instruction in README to install termonad at arch linux, I got this error:
![截屏2020-09-24 下午12 47 09](https://user-images.githubusercontent.com/50952350/94102208-3229b400-fe64-11ea-8fe2-c0294257aea5.png)

**Comment by c4dr01d** [comment] 2020-09-24 04:51
I'm using stack version is 2.3.1

**Comment by cdepillabout** [comment] 2020-09-24 05:32
@c4dr01d Could you post the full build output?

From this screen-shot, it is not clear why `gi-glib` is failing to build.

**Comment by c4dr01d** [comment] 2020-09-24 06:29
@cdepillabout 
![截屏2020-09-24 下午2 28 24](https://user-images.githubusercontent.com/50952350/94108678-4f657f00-fe72-11ea-8489-23d8f8e85ede.png)

**Comment by cdepillabout** [comment] 2020-09-24 06:59
The error is:

```
Unknown GIR element "docsection" when processing namespace "GLib", aborting.
```

These types of error can be caused by using either too new or too old versions of the gtk/glib-related libraries.

Termonad depends on the `haskell-gi` family of Haskell libraries (and this includes the `gi-glib` package that you're having trouble with).  The `haskell-gi` and `gi-glib` package versions are determined by the `resolver` in the `stack.yaml` file.

If you're a Haskeller and want to try to figure out a fix for this, I recommend switching the `resolver` to nightly and seeing if you can build with the latest versions of all the `haskell-gi` libraries.  There may be some small changes you have to make in the termonad source code, but it shouldn't be much.  If you can't get this working, then I recommend just trying to get the latest version of `gi-glib` building on your system.  You can post an issue on the upstream `haskell-gi` repo if you can't get this working.  It is possible that `haskell-gi` doesn't yet support the version of glib you get from Arch.  The `haskell-gi` maintainer will probably want to know about this.

If you're not a Haskeller and you just want to get this working, I recommend building with `nix`.  If you install `nix`, you should be able to build Termonad with the command `nix-build`.

**Comment by c4dr01d** [comment] 2020-09-24 09:10
@cdepillabout I just search the upstream, I founded existing issue for my question.I'll post my error to there, but the way, thanks for your answer.

**Comment by cdepillabout** [comment] 2020-09-24 13:49
@c4dr01d I'll close this for now, but if you find that something can be done in Termonad to fix this, please feel fee to re-open.

Also, please post a link to the upstream issue so people who find this issue in the future know where to get more information.

**Closed by cdepillabout** 2020-09-24 13:49 UTC
Labels: bug, help wanted

**Comment by c4dr01d** [comment] 2020-09-25 02:30
I founded this [#318](https://github.com/haskell-gi/haskell-gi/issues/318) issue can fix the docsection problem temporarily, ths upstream repository maintainer say will fix the later.
