### ISSUE TITLE
Hotkeys like Ctrl-A and Alt-b are not working

### ISSUE THREAD

**Issue by yaitskov** [cdepillabout/termonad#187] opened 2021-05-09 02:41 UTC
in all good terminals I used before Alt-b is moving cursor a word backward.

**Comment by cdepillabout** [comment] 2021-05-09 05:34
Alt-b is a keyboard shortcut for `bash` (and probably other similar shells):

http://www.keyxl.com/aaaf192/83/Linux-Bash-Shell-keyboard-shortcuts.htm

Termonad shouldn't be intercepting this keyboard shortcut.

I'm not sure what could be your problem.  What happens when you press Alt-b?  Are you using a shell that supports the Alt-b shortcut (like bash in emacs-keyboard mode)?  Are you sure Alt-b isn't being swallowed by your window manager?

**Comment by yaitskov** [comment] 2021-05-09 23:49
I thought terminal emulator intercepts such short cuts.
Ctrl-A and Alt-b don't work and produce garbage sort of "[^"
Switching keyboard layout is glitchy (I use double shift).
I run Debian 10 and got termonad through `nix-shell -p pkgs.haskellPackages.termonad` in gnome-terminal.
I didn't do special shell configuration and keen to stock bash.

**Comment by cdepillabout** [comment] 2021-05-10 00:51
Hmm, I'm not sure what your problem could be.  I haven't run into this myself, nor have I heard of anyone else run into this.

My guess is that this isn't a Termonad problem, since there isn't any code in Termonad for swallowing shortcut keys like Ctrl-A or Alt-b.

I'll keep this issue open for a while in case anyone else runs into this problem.

**Comment by cdepillabout** [comment] 2021-06-17 01:36
I'm going to go ahead and close this since I can't reproduce it, and it doesn't seem like anyone else has run into the same problem.

If you do some more digging and can figure out the underlying problem, I'm happy to re-open this issue though.

-------------------------------

>  I run Debian 10 and got termonad through nix-shell -p pkgs.haskellPackages.termonad in gnome-terminal.

Also, in general, if you want to get termonad through nixpkgs, you should get it from the top-level `termonad-with-packages`:

```console
$ nix-shell -p termonad-with-packages
```

This is a wrapped version of Termonad so that it knows how to find GHC with an appropriate package database.

**Closed by cdepillabout** 2021-06-17 01:36 UTC
Labels: question
